export const mockData = {
    SkinnyCardDetailsInput: [{
        location: "Bushwick",
        streetAddress: "24 cornelia st apt 2",
        price: 5500,
        fee: true,
        beds: 3,
        baths: 2,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "Williamsburg",
        streetAddress: "1235 Carlyse 2",
        price: 5500,
        beds: 0,
        fee: false,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "Fort Green",
        streetAddress: "Mrytle Ave #c203",
        price: 5500,
        beds: 2,
        fee: false,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "Crown Heights",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        fee: true,
        baths: 1,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "Lower East Side",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 1,
        baths: 1.5,
        fee: false,
        favorite: true,
        isNew: false,
        onMarket: false,
    },{
        location: "Tribeca",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 4,
        fee: false,
        baths: 5,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "Upper East Side",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        fee: true,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "Bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        isNew: false,
        onMarket: false,
    },
    {
        location: "7bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        isNew: false,
        onMarket: false,
    }
],
}
