export const mockData = {
    SkinnyCardDetailsInput: [{
        location: "1bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 2,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "2bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 0,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 2,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 1,
        baths: 1.5,
        favorite: true,
        isNew: false,
        onMarket: false,
    },{
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 4,
        baths: 5,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        isNew: false,
        onMarket: false,
    },
    {
        location: "7bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: false,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        onMarket: false,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: false,
        isNew: true,
        onMarket: true,
    },
    {
        location: "bushwick",
        streetAddress: "24 cornelia st",
        price: 5500,
        beds: 3,
        baths: 1.5,
        favorite: true,
        isNew: false,
        onMarket: false,
    }
],
}
